import Head from "next/head";

const SITE_NAME = "100 Pixel Art";
const SITE_URL = "100pixelart.nabettu.com";

export default function Home({ children }) {
  return (
    <div>
      <Head>
        <title>{SITE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{SITE_NAME}</h1>

        <p></p>
      </main>

      <footer>
        <a
          href="https://twitter.com/nabettu"
          target="_blank"
          rel="noopener noreferrer"
        >
          create by nabettu
        </a>
      </footer>
    </div>
  );
}
